FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY services/ereceiver.py /app/services/ereceiver.py
COPY data /app/data
COPY utils /app/utils
COPY log /app/log

CMD ["uvicorn", "services.ereceiver:app", "--host", "0.0.0.0", "--port", "8080"]

EXPOSE 8080


