FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY services/databroker.py /app/services/databroker.py
COPY data /app/data
COPY utils /app/utils
COPY log /app/log

CMD ["uvicorn", "services.databroker:app", "--host", "0.0.0.0", "--port", "8081"]

EXPOSE 8081
