FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY services/evalidator.py /app/services/evalidator.py
COPY data /app/data
COPY utils /app/utils
COPY log /app/log

CMD ["uvicorn", "services.evalidator:app", "--host", "0.0.0.0", "--port", "8082"]

EXPOSE 8082
