FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY services/eprocessor.py /app/services/eprocessor.py
COPY data /app/data
COPY utils /app/utils
COPY log /app/log

CMD ["uvicorn", "services.eprocessor:app", "--host", "0.0.0.0", "--port", "8083"]

EXPOSE 8083
